<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class IconSeeder extends Seeder
{
    public function run(): void
    {
        $icons = [
            ['id' => 482, 'name' => 'face'],
            ['id' => 483, 'name' => 'house'],
            ['id' => 581, 'name' => 'apps'],
            ['id' => 582, 'name' => 'select_all'],
            ['id' => 583, 'name' => 'token'],
            ['id' => 584, 'name' => 'settings'],
            ['id' => 585, 'name' => 'check_circle'],
            ['id' => 586, 'name' => 'emoji_flags'],
            ['id' => 587, 'name' => 'query_stats'],
            ['id' => 588, 'name' => 'workspace_premium'],
            ['id' => 589, 'name' => 'emoji_objects'],
            ['id' => 590, 'name' => 'groups'],
            ['id' => 591, 'name' => 'arrow_circle_down'],
            ['id' => 592, 'name' => 'double_arrow'],
            ['id' => 593, 'name' => 'monetization_on'],
            ['id' => 595, 'name' => 'science'],
            ['id' => 596, 'name' => 'arrow_circle_up'],
            ['id' => 647, 'name' => 'api'],
            ['id' => 648, 'name' => 'autorenew'],
            ['id' => 649, 'name' => 'backup'],
            ['id' => 650, 'name' => 'close_fullscreen'],
            ['id' => 651, 'name' => 'dynamic_form'],
            ['id' => 652, 'name' => 'eco'],
            ['id' => 653, 'name' => 'explore'],
            ['id' => 654, 'name' => 'extension'],
            ['id' => 655, 'name' => 'highlight_alt'],
            ['id' => 656, 'name' => 'model_training'],
            ['id' => 657, 'name' => 'online_prediction'],
            ['id' => 658, 'name' => 'open_with'],
            ['id' => 659, 'name' => 'settings_cell'],
            ['id' => 660, 'name' => 'visibility'],
            ['id' => 661, 'name' => 'contact_mail'],
            ['id' => 662, 'name' => 'call_merge'],
            ['id' => 663, 'name' => 'biotech'],
            ['id' => 664, 'name' => 'signal_wifi_4_bar_lock'],
            ['id' => 665, 'name' => 'gps_fixed'],
            ['id' => 666, 'name' => 'cloud_download'],
            ['id' => 667, 'name' => 'cloud_queue'],
            ['id' => 668, 'name' => 'laptop_chromebook'],
            ['id' => 669, 'name' => 'gamepad'],
            ['id' => 670, 'name' => 'headset_mic'],
            ['id' => 671, 'name' => 'security'],
            ['id' => 672, 'name' => 'colorize'],
            ['id' => 673, 'name' => 'center_focus_strong'],
            ['id' => 674, 'name' => 'flare'],
            ['id' => 675, 'name' => 'local_airport'],
            ['id' => 676, 'name' => 'local_fire_department'],
            ['id' => 677, 'name' => 'map'],
            ['id' => 678, 'name' => 'local_shipping'],
            ['id' => 679, 'name' => 'local_mall'],
            ['id' => 680, 'name' => 'campaign'],
            ['id' => 681, 'name' => 'account_tree'],
            ['id' => 682, 'name' => 'wifi'],
            ['id' => 683, 'name' => 'storefront'],
            ['id' => 684, 'name' => 'sports_esports'],
            ['id' => 685, 'name' => 'poll'],
            ['id' => 686, 'name' => 'coronavirus'],
            ['id' => 687, 'name' => 'domain'],
            ['id' => 688, 'name' => 'elderly'],
            ['id' => 689, 'name' => 'smoke_free'],
            ['id' => 690, 'name' => 'ac_unit'],
            ['id' => 691, 'name' => 'navigation'],
            ['id' => 692, 'name' => 'my_location'],
            ['id' => 702, 'name' => 'hardware'],
            ['id' => 769, 'name' => 'auto_fix_high'],
            ['id' => 989, 'name' => 'microbiology'],
            ['id' => 990, 'name' => 'precision_manufacturing'],
            ['id' => 991, 'name' => 'brightness_auto'],
            ['id' => 992, 'name' => 'arrow_cool_down'],
            ['id' => 993, 'name' => 'rule_settings'],
            ['id' => 994, 'name' => 'qr_code_scanner'],
            ['id' => 995, 'name' => 'cardiology'],
            ['id' => 996, 'name' => 'arrows_output'],
            ['id' => 997, 'name' => 'recenter'],
            ['id' => 998, 'name' => 'approval_delegation'],
            ['id' => 999, 'name' => 'satellite_alt'],
            ['id' => 1000, 'name' => 'database'],
            ['id' => 1001, 'name' => 'network_intelligence'],
            ['id' => 1002, 'name' => 'globe_book'],
            ['id' => 1003, 'name' => 'highlight'],
            ['id' => 1004, 'name' => 'network_check'],
            ['id' => 1005, 'name' => 'paid'],
            ['id' => 1006, 'name' => 'blur_off'],
            ['id' => 1007, 'name' => 'memory'],
            ['id' => 1008, 'name' => 'lightbulb_circle'],
            ['id' => 1009, 'name' => 'display_settings'],
            ['id' => 1010, 'name' => 'broadcast_on_home'],
            ['id' => 1011, 'name' => 'devices_other'],
            ['id' => 1012, 'name' => 'troubleshoot'],
            ['id' => 1013, 'name' => 'clock_arrow_down'],
            ['id' => 1014, 'name' => 'grain'],
            ['id' => 1015, 'name' => 'health_and_safety'],
            ['id' => 1016, 'name' => 'cruelty_free'],
            ['id' => 1017, 'name' => 'shield_with_heart'],
            ['id' => 1018, 'name' => 'nest_farsight_eco'],
            ['id' => 1019, 'name' => 'japanese_flag'],
            ['id' => 1020, 'name' => 'interactive_space'],
            ['id' => 1021, 'name' => 'schedule'],
            ['id' => 1022, 'name' => 'responsive_layout'],
        ];

        foreach ($icons as $icon) {
            DB::table('icons')->insert($icon);
        }
    }
}